# Generated by Django 5.2.8 on 2025-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=20)),
            ],
        ),
    ]
