# Generated by Django 5.2.8 on 2025-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigomateria', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fkest', models.ManyToManyField(to='app1.estudiante')),
            ],
        ),
    ]
