# Generated by Django 5.2.8 on 2025-11-12 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(verbose_name=20)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fkinst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.instituto'),
        ),
    ]
