# Generated by Django 5.2.8 on 2025-11-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_instituto_estudiante_fkinst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo',
        ),
        migrations.CreateModel(
            name='IdentifEstudiantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_emision', models.DateField()),
                ('fkest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.estudiante')),
            ],
        ),
    ]
