# Generated by Django 5.2.8 on 2025-11-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigocli', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigopedido', models.CharField(max_length=10)),
                ('fechaentrega', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fkcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
            ],
        ),
    ]
