# Generated by Django 5.2.8 on 2025-11-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fkcateg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.categoria'),
        ),
    ]
