# Generated by Django 5.2.8 on 2025-11-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_producto_codigo_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fkcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.categoria'),
        ),
    ]
